{% set name = "typescript-eslint-parser" %}
{% set version = "5.28.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/typescript-eslint/typescript-eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 340064e8783d28367ccac2f8efbe3ff733bb9cfb1fa97172ac0f79800aac0d6b

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
    # this is necessary due to https://github.com/nodejs/node/issues/42397#issuecomment-1072931291
    - nodejs !=16.14.2
  host:
    - nodejs
    - nodejs !=16.14.2
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@typescript-eslint/parser  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\@typescript-eslint\parser exit 1  # [win]

about:
  home: https://github.com/typescript-eslint/typescript-eslint
  license: MIT
  license_file:
    - LICENSE
    - packages/parser/ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
    - jens-ox
