{% set name = "typescript-eslint-parser" %}
{% set version = "6.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/typescript-eslint/typescript-eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6560ebff03d67fd3f224770fbdeb9561bd97e185b2df01d54c4a7599fc481b3d

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - nodejs
    - make
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
    - yarn
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@typescript-eslint/parser  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\@typescript-eslint\parser exit 1  # [win]

about:
  home: https://github.com/typescript-eslint/typescript-eslint
  license: MIT
  license_file:
    - LICENSE
    - packages/parser/ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
