{% set name = "typescript-eslint-parser" %}
{% set version = "6.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/typescript-eslint/typescript-eslint/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 56fe1a4c7cdea4577566dae9d858dc793ad4d7d50178ed3106bd3832dddbad0e

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - nodejs
    # this is necessary due to https://github.com/nodejs/node/issues/42397#issuecomment-1072931291
    - nodejs !=16.14.2
  host:
    - nodejs
    - nodejs !=16.14.2
    - yarn <2
  run:
    - nodejs

test:
  commands:
    - test -d $PREFIX/lib/node_modules/@typescript-eslint/parser  # [unix]
    - if not exist %LIBRARY_INC%\lib\node_modules\@typescript-eslint\parser exit 1  # [win]

about:
  home: https://github.com/typescript-eslint/typescript-eslint
  license: MIT
  license_file:
    - LICENSE
    - packages/parser/ThirdPartyLicenses.txt
  summary: Find and fix problems in your JavaScript code.

extra:
  recipe-maintainers:
    - xhochy
    - jens-ox
